spring:
  datasource:
    password: India@1234
    url: jdbc:postgresql://localhost:5432/emp
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

